config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get '/posts' => 'posts#index'

  resources :users, only: [:show, :new]
  resources :posts do
    collection do
      get 'item'
      get 'ranking'
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/post.rb
class Post < ApplicationRecord
# class Post < ActiveRecord::Base
  validates :name_id, :about, :image, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :design

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.search(search)
    return Post.all unless search
    Post.where(name_id: search) 
    Post.where(['about LIKE ?', "%#{search}%"])
    # return Post.all unless search
    # Post.where(['name_id LIKE ?', "%#{search}%"])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
    post_ids = Like.group(:post_id).order('count_post_id DESC').limit(5).count(:post_id).keys
    @posts = post_ids.map { |id| Post.find(id) }
  end

  def item
    @posts = Post.order("created_at DESC").page(params[:page]).per(9)
    @post = Post.new
  end

  def ranking
    post_ids = Like.group(:post_id).order('count_post_id DESC').count(:post_id).keys
    posts = post_ids.map { |id| Post.find(id) }
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(9)
  end

  def search
    @posts = Post.search(params[:search]).page(params[:page]).per(9)
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    unless @post.save
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to root_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.update(post_params)
      redirect_to root_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @like= Like.new
    @comments = @post.comments
    @comment = Comment.new
  end

  private
  def post_params
    params.require(:post).permit(:about, :image, :name, :name_id).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_all_items.html.erb
<div class="items-container">
  <% @posts.each do |post| %>
  <div class="item-container">
    <div class="item-image">
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.image.url, :size =>'200x250'%>
      <% end %>
    </div>
    <div class="item-design">
      <%= Design.find(post.name_id).name %>
    </div>
    <div class="item-like-btn">
      <i class="fas fa-heart"></i>
      <%= post.liked_users.count %>
    </div>
  </div>
  <% end %>
</div>
<div class="pagination-bar">
  <%= paginate @posts %>
</div>

app/views/posts/_header-search-bar.html.erb
<div class="search-bar">
  <div class="select_search-bar">
    <p>Category</p>
    <%= form_tag(search_posts_path, :method => 'get') do %>
      <%= select_tag "search", options_for_select([["クラシック", 1],["フェミニン", 2],["カジュアル", 3],["シンプル", 4],["メンズライク", 5],["スポーティ", 6]]) %>
      <%= submit_tag 'Search', :name => nil %>
    <% end %>
  </div>
  <div class="about_search-bar">
    <p>About</p>
    <%= form_tag(search_posts_path, :method => 'get') do %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :name => nil %>
    <% end %>
  </div>
</div>

app/views/posts/_header.html.erb
<div class="header">
  <div class="header-title">
    <a href="/" class="title_logo">fitWatch</a>
  </div>
  <div class="header_menu">
    <div class="header_menu-list">
      <ul>
        <li><%= link_to"ranking", ranking_posts_path %></li>
        <li><%= link_to"item", item_posts_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to"post", new_post_path %></li>
        <li><%= link_to current_user.nickname, user_path(current_user.id) %></li>
        <li><%= link_to"sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to"sign in", new_user_session_path %></li>
        <li><%= link_to"sign up", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/create.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
      <div class="success-container">   
        <div class="success">
          <h3>
            投稿が完了しました。
          </h3>
        </div>
      </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
      <div class="new_post_container">
        <div class="new_post-header">
          <p>Post your favorite watch</p>
        </div>
        <div class="new_post-form">
          <%= form_for(@post) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="input-form">
            <p>・Image</p>
            <%= image_tag @post.image.url, id: :image_prev if @post.image? %>
            <%= f.file_field :image, id: :form_image %>
            <p>・Design</p>
            <%= f.collection_select :name_id, Design.all, :id, :name, prompt: "--", class: "form_design", required: true %>
            <p>・About</p>
            <%= f.text_area :about, :maxlength => "300", class:"form_about", required: true %>
            <%= f.submit "Send", class:"form_send-button" %>
          <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
      <div class="main-container">
        <div class="ranking-container">
          <% num = 0 %>
          <% @posts.each do |post| %>
          <div class= "ranking_post">
          <% num+= 1 %>
            <div class="ranking_order">
              <% if num==1 %>
                <i class="fas fa-crown"></i>
                <%= "no.#{num}" %>
              <% else %>
                <%= "no.#{num}" %>
              <% end %>
            </div>
            <%= link_to post_path(post.id), class: "post-image" do %>
              <%= image_tag post.image.to_s %>
            <% end %>
            <div class= "like-btn">
              <i class="fas fa-heart"></i>
              <h3><%= post.liked_users.count %></h3>
            </div>
          </div>
          <% end %>
        </div>
        <%= link_to "more", ranking_posts_path, class:"ranking-more-button" %>
      </div>
  </div>
</div>

app/views/posts/item.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
      <%= render 'all_items' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
      <div class="new_post_container">
        <div class="new_post-header">
          <p>Post your favorite watch</p>
        </div>
        <div class="new_post-form">
          <%= form_for(@post) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="input-form">
            <p>・Image</p>
            <% if @post.image? %>
              <%= image_tag @post.image.url, id: :image_prev  %>
            <% else %>
              <%= image_tag "/no-image.png", id: :image_prev  %>
            <% end %>
            <%= f.file_field :image, id: :form_image %>
            <p>・Design</p>
            <%= f.collection_select :name_id, Design.all, :id, :name, prompt: "--", class: "form_design" %>
            <p>・About</p>
            <%= f.text_area :about, :maxlength => "300", class:"form_about" %>
            <%= f.submit "Send", class:"form_send-button" %>
          <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/posts/ranking.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
    <%= render 'header-search-bar' %>
      <%= render 'all_items' %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
    <%= render 'header-search-bar' %>
      <%= render 'all_items' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="wrapper">
  <div class="main">
    <%= render 'header' %>
      <div class="show_post_container">
        <div class="show_post_container--item">
          <%= image_tag @post.image.url %>
          <div class="show_post_container--item-details">
            <div class="likes-comments">
              <div id="likes_buttons_<%= @post.id %>", class="likes_buttons">
                <%= render partial: "likes/like", locals: { post: @post } %>
              </div>
              <div class="comments-buttons">
                <i class="far fa-comment-dots"></i><%= @post.comments.count %>
              </div>
            </div>
            <div class="show_post_container--item-details--design">
              <%= Design.find(@post.name_id).name %>
            </div>
            <div class="show_post_container--item-details--about">
              <%= @post.about %>
            </div>
            <h3><%= @post.user.nickname %></h3>
            <% if user_signed_in? && current_user.id == @post.user_id %>
              <%= link_to "Edit", edit_post_path(@post.id), class:"patch_button" %>
              <%= link_to "Delete", post_path(@post.id), method: :delete, class:"delete_button" %>
            <% end %>
          </div>
          <%= link_to "Back", posts_path, class:"back_button" %>

          <div class= "show_post_container--item-comments">
            <h3>コメント</h3>
            <% @comments.each do |comment| %>
            <div class="show_post_container--item-comments--list">
              <div class="comment-message">
                <%= comment.message %>
              </div>
              <div class="comment-name">
                <%= comment.user.nickname %>
              </div>
              <% if user_signed_in? && current_user.id == comment.user_id %>
                <div class="comment-delete">
                  <%= link_to post_comment_path(comment.post_id,comment.id), method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
            <% end %>
            <div class="show_post_comment-form">
              <%= render partial: "comments/comment", locals: { post: @post } %>
            </div>
          </div>

        </div>
      </div>
  </div>
</div>